<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['book_id'=> "1",  'author'=> "Vassilis Vassilikos" ,'publisher'=>'Judi Rhodes','year'=>2003,'description'=>'The ordinary life of a boy will change forever as a childhood friend enters his life.\nThe childhood friend claims the boy has a DNA strain which very likely offers the key to cure several crippling diseases. Tests will have to be done, but the key to save millions of lives is within the grasp of science through this DNA strain. Concerned of the situation and a little distrusful of this childhood friend, the boy hesitantly agrees to the proposal, there\'s no way this is all a lie, right? If it is, a terrible choice might have been made.\nBut what if this childhood friend speaks only lies. Or what if this is all far bigger than what has been told. How could an ordinary boy come out of this situation in a better way. Only one way to find out.'],
            ['book_id'=> "2",  'author'=> "Douglas Adams" ,'publisher'=>'Illinois Historic Preservation Agency','year'=>2010,'description'=>'The calm life of a teenage boy will be changed completely as a friendly acquaintance enters his life.\nThe friendly acquaintance claims the teenage boy is now the citizen of a different country. The old country has just been taken over by an enemy force, everybody who wishes to leave this new nation has 3 days to do so. Unsure about everything, including this friendly acquaintance, the teenage boy hastily agrees to the proposal, it all seemed rather odd, but there was no time to waste and a choice had to be made.\nBut what if this friendly acquaintance is trying to manipulate the situation. Or what if this proposal is wrong or missing important details. How could an ordinary teenage boy end up in a situation like this. Time to find out.'],
            ['book_id'=> "3",  'author'=> "Orhan Pamuk" ,'publisher'=>'Rabenold&binder P.c','year'=>2021,'description'=>'The secluded life of a young guy will be permanently altered as a strange woman enters his life.\nThe strange woman claims the young guy is a host to an alien being, one who is still benign right now, but could take over the brain when it has grown to maturity. Fortunately there\'s a way to get rid of it and potentially unlock the key to get rid of all these aliens. Certain of the truth in this situation and of this strange woman, the young guy cautiously agrees to the proposal, but for some reason a nagging feeling of \'this is a bad choice\' won\'t go away.\nBut what if this strange woman is not speaking the truth. Or what if everything told is completely true. How could an ordinary young guy be this important to the situation. Time will tell.'],
            ['book_id'=> "4",  'author'=> "Alejo Carpentier" ,'publisher'=>'Advanced Multimedia Concepts Inc','year'=>2007,'description'=>'The hectic life of a young guy take a sharp turn as a lost friend enters his life.\nThe lost friend claims the young guy is never going to believe his eyes, dragons have returned and are currently gathering at the nearby mountain range. Nobody knows why they\'re back nor what they have planned, but it\'s safe to take a look from a distance. Certain of the truth in this situation and of this lost friend, the young guy somewhat grudgingly agrees to the proposal, it\'s probably best to get to the bottom of this as soon as possible.\nBut what if this lost friend can\'t be trusted. Or what if there\'s a change of mind. How could an ordinary young guy find out what\'s happening without help. Time will tell.'],
            ['book_id'=> "5",  'author'=> "Ally Carter" ,'publisher'=>'Liftedsites','year'=>2004,'description'=>'The carefree life of a teenage girl take a sharp turn as a stranger enters her life.\nThe stranger claims the teenage girl is the descendant of a lineage of warriors who have protected the world throughout history. The time has come to step in the footsteps of these ancestors and help protect the world of today. Concerned of the situation and a little distrusful of this stranger, the teenage girl somewhat grudgingly agrees to the proposal, it might be a mistake, but both options could\'ve been the mistake, one had to be chosen.\nBut what if this stranger is pulling a prank. Or what if the wrong person was picked for this. How could an ordinary teenage girl play a part in all this. No turning back now though.'],
            ['book_id'=> "6",  'author'=> "Karen Russell" ,'publisher'=>'Cosmos Systems Softwares Ltd','year'=>2008,'description'=>'The relaxed life of a young girl might be changing forever as a strange girl enters her life.\nThe strange girl claims the young girl is chosen to be one of the few lucky people who get to leave Earth on the enormous spaceship planned to leave before the imminent end of Earth. Skeptical of this situation and of this strange girl, the young girl oddly enthusiastically agrees to the proposal, it might be a mistake, but both options could\'ve been the mistake, one had to be chosen.\nBut what if this strange girl is trying be misleading. Or what if the situation has changed or will change. How could an ordinary young girl end up in a situation like this. Only one way to find out.'],
            ['book_id'=> "7",  'author'=> "Melissa Broder" ,'publisher'=>'Stewart Enterprises','year'=>2002,'description'=>'The casual life of a elderly woman has a chance to change, for better or worse, as a strange boy enters her life.\nThe strange boy claims the elderly woman is needed right now in the town center. A dangerous criminal is holding people hostage and is asking for 3 specific people to show up. The identity of the criminal is unknown, but innocent lives are at stake. Unsure about everything, including this strange boy, the elderly woman somewhat reluctantly agrees to the proposal, there\'s no way this is all a lie, right? If it is, a terrible choice might have been made.\nBut what if this strange boy is not speaking the truth. Or what if all this is an elaborate trap. How could an ordinary elderly woman be this important to the situation. Time will tell.'],
            ['book_id'=> "8",  'author'=> "Nathan Hill" ,'publisher'=>'Modern Machine Shop','year'=>2007,'description'=>'The secluded life of a man has a chance to change, for better or worse, as a strange man enters his life.\nThe strange man claims the man can pick one person in the entire world and that person will die. An evil dictator? Some crazy terrorist? A childhood bully? Pick whoever you wish, this man will supposedly take care of it, but there\'s only 12 hours to decide. Believing both the situation and this strange man, the man warily agrees to the proposal, this whole situation is both exciting and terrifying at the same time, but surely the right choice was made.\nBut what if this strange man is just a crazy person. Or what if there\'s a change of mind. How could an ordinary man be needed for a situation like this. Time to find out.'],
            ['book_id'=> "9",  'author'=> "Henry Miller" ,'publisher'=>'Cfa Corporation','year'=>2006,'description'=>'The laid-back life of a elderly woman is going the complete opposite way as a strange girl enters her life.\nThe strange girl claims the elderly woman is part of a secret agent program and his leaders are on their way to \'activate\' him through a secret code word. The person claims to have escaped activation and offers escape from these supposed leaders. Certain of the truth in this situation and of this strange girl, the elderly woman tentatively agrees to the proposal, no matter what, something has to be done in this situation, hopefully this was the right choice.\nBut what if this strange girl is trying be misleading. Or what if all this is an elaborate trap. How could an ordinary elderly woman find out what\'s happening without help. Only one way to find out.'],
            ['book_id'=> "10", 'author'=> "Marcel Proust" ,'publisher'=>'Os Lubrano','year'=>2015,'description'=>'The relaxed life of a young guy might turn out differently as a childhood friend enters his life.\nThe childhood friend claims the young guy is one of the rare few people in possession of a guardian animal spirit. It\'s widely known these exist and rituals are held on a near weekly basis to connect with these guardian spirits, now its time to be the center of that ritual. Distrusful of both this situation and of this childhood friend, the young guy hastily agrees to the proposal, there\'s no way this is all a lie, right? If it is, a terrible choice might have been made.\nBut what if this childhood friend speaks only lies. Or what if somebody is orchestrating all of this. How could an ordinary young guy come out of this situation in a better way. We\'re about to find out.'],
            //...
        ];
        DB::table('details')->insert($data); // Query Builder approach
    }
}
